-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 20:41:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maturitni_cetba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maturitni_cetba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maturitni_cetba` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci ;
USE `maturitni_cetba` ;

-- -----------------------------------------------------
-- Table `maturitni_cetba`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`teacher` (
  `id_teacher` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(69) NULL,
  `lastName` VARCHAR(69) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_teacher`));


-- -----------------------------------------------------
-- Table `maturitni_cetba`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`class` (
  `id_class` INT NOT NULL AUTO_INCREMENT,
  `firstYear` YEAR NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `teacher_id` INT NOT NULL,
  `lockTime` DATETIME NULL DEFAULT NULL,
  `lockCount` INT NULL,
  PRIMARY KEY (`id_class`),
  INDEX `fk_class_teacher1_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `maturitni_cetba`.`teacher` (`id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturitni_cetba`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`student` (
  `id_student` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(69) NULL,
  `lastName` VARCHAR(69) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`id_student`),
  INDEX `fk_student_class_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `maturitni_cetba`.`class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `maturitni_cetba`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`book` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `century` ENUM('18.', '19.', '20./21.') NOT NULL,
  `category` ENUM('cz', 'svet') NOT NULL,
  `active` ENUM('yes', 'no') NOT NULL DEFAULT 'yes',
  `link` VARCHAR(255) NULL,
  PRIMARY KEY (`id_book`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturitni_cetba`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`author` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(69) NULL,
  `lastName` VARCHAR(69) NOT NULL,
  PRIMARY KEY (`id_author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturitni_cetba`.`book_has_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`book_has_author` (
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`),
  INDEX `fk_bookList_has_author_author1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_bookList_has_author_bookList1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookList_has_author_bookList1`
    FOREIGN KEY (`book_id`)
    REFERENCES `maturitni_cetba`.`book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookList_has_author_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `maturitni_cetba`.`author` (`id_author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturitni_cetba`.`student_has_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`student_has_book` (
  `student_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `dateAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `order` INT NOT NULL,
  `state` ENUM('unread', 'read', 'done') NOT NULL DEFAULT 'unread',
  `teachersNote` VARCHAR(255) NULL,
  PRIMARY KEY (`student_id`, `book_id`),
  INDEX `fk_student_has_bookList_bookList1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_student_has_bookList_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_bookList_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `maturitni_cetba`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_bookList_bookList1`
    FOREIGN KEY (`book_id`)
    REFERENCES `maturitni_cetba`.`book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `maturitni_cetba`.`swap_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturitni_cetba`.`swap_request` (
  `id_swap_request` INT NOT NULL AUTO_INCREMENT,
  `id_student` INT NOT NULL,
  `id_originalBook` INT NOT NULL,
  `id_newBook` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `accepted` ENUM('pending', 'yes', 'no') NOT NULL DEFAULT 'pending',
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`id_swap_request`),
  INDEX `fk_student_student1_idx` (`id_student` ASC) VISIBLE,
  INDEX `fk_bookList_book1_idx` (`id_originalBook` ASC) VISIBLE,
  INDEX `fk_bookList_book2_idx` (`id_newBook` ASC) VISIBLE,
  INDEX `fk_changeRequests_teacher1_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_student1`
    FOREIGN KEY (`id_student`)
    REFERENCES `maturitni_cetba`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookList_book1`
    FOREIGN KEY (`id_originalBook`)
    REFERENCES `maturitni_cetba`.`book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookList_book2`
    FOREIGN KEY (`id_newBook`)
    REFERENCES `maturitni_cetba`.`book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_changeRequests_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `maturitni_cetba`.`teacher` (`id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
